[package]
name = "dlog_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
elliptic-curve = "0.11"
k256 = "0.10"
rand = "0.8"
num-bigint = "0.4"
num-traits = "0.2.19"
serde = {version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
lazy_static = "1.5.0"