[package]
name = "dlog_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
k256 = "0.10"
rand = "0.8"
serde_json = "1.0.120"
hex = "0.4.3"
clap = { version = "4.5.11", features = ["derive"] }